### ISSUE TITLE
好孩子的变量怎么填？

### ISSUE THREAD

**Issue by xiaolong52** [Shawn220528/scripts#2]
按照说明填写报错

开始进行登录获取token

登录失败： unionId、openId和支付宝用户ID不能同时为空！

签到失败： 请求的方法必须传递有效的access_token

**Comment by Shawn220528** [comment]
抓包关键字method=gb.member.new.openid.login，里面有个参数params=xxx 把xxx填入变量即可

**Comment by xiaolong52** [comment]
可以了，谢谢
抓错包了。
