### ISSUE TITLE
大佬有群吗？？

### ISSUE THREAD

**Issue by Jim-oVo** [Shawn220528/scripts#9]

**Comment by Jim-oVo** [comment]
大佬可以试试罗莱、慕思、沃尔沃、蜜雪冰城、味道馆小程序吗?
姿美健康APP种稻穗、奇瑞汽车app吗？

**Comment by Shawn220528** [comment]
https://t.me/+EwACkZts65wwZTM9

**Comment by OwnerCM** [comment]
> https://t.me/+EwACkZts65wwZTM9

大佬，链接过期了，能否重新发一个，谢谢！
